packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

overrides:
  "@internationalized/date": "3.7.0"
  "@internationalized/number": "3.5.0"
  "@ark-ui/react": "5.30.0"
  "@chakra-ui/react": "3.30.0"
  "@saas-ui/react": "3.0.0-next.51"
  "@saas-ui/forms": "3.0.0-next.52"
  "@saas-ui/modals": "3.0.0-next.52"
  "@saas-ui/hooks": "3.0.0-next.3"
  "@saas-ui-pro/react": "1.0.0-next.4"

patchedDependencies:
  "@confect/cli@10.0.0-next.9": "patches/@confect__cli@10.0.0-next.9.patch"
  "@tanstack/start-plugin-core@1.171.18": "patches/@tanstack__start-plugin-core@1.171.18.patch"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "esbuild"
  - "lefthook"
  - "msgpackr-extract"
