/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as EvaluateRouteImport } from './routes/evaluate'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as ReportEvaluationIdRouteImport } from './routes/report.$evaluationId'
import { Route as MaestroPackIdRouteImport } from './routes/maestro.$packId'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CheckoutReportIdRouteImport } from './routes/checkout.$reportId'
import { Route as BuildPackPackIdRouteImport } from './routes/build-pack.$packId'
import { Route as WorkspaceWorkflowsRouteImport } from './routes/_workspace.workflows'
import { Route as WorkspaceSourcesRouteImport } from './routes/_workspace.sources'
import { Route as WorkspaceSettingsRouteImport } from './routes/_workspace.settings'
import { Route as WorkspaceRunsRouteImport } from './routes/_workspace.runs'
import { Route as WorkspaceOnboardingRouteImport } from './routes/_workspace.onboarding'
import { Route as WorkspaceNotificationsRouteImport } from './routes/_workspace.notifications'
import { Route as WorkspaceLegalRouteImport } from './routes/_workspace.legal'
import { Route as WorkspaceIntegrationsRouteImport } from './routes/_workspace.integrations'
import { Route as WorkspaceHealthRouteImport } from './routes/_workspace.health'
import { Route as WorkspaceDocumentsRouteImport } from './routes/_workspace.documents'
import { Route as WorkspaceDataMapRouteImport } from './routes/_workspace.data-map'
import { Route as WorkspaceDataLifecycleRouteImport } from './routes/_workspace.data-lifecycle'
import { Route as WorkspaceCapabilitiesRouteImport } from './routes/_workspace.capabilities'
import { Route as WorkspaceBrainRouteImport } from './routes/_workspace.brain'
import { Route as WorkspaceBillingRouteImport } from './routes/_workspace.billing'
import { Route as WorkspaceApiRouteImport } from './routes/_workspace.api'
import { Route as WorkspaceAnalyticsRouteImport } from './routes/_workspace.analytics'
import { Route as WorkspaceAgentsRouteImport } from './routes/_workspace.agents'
import { Route as WorkspaceAdminRouteImport } from './routes/_workspace.admin'
import { Route as BuildPackPackIdIndexRouteImport } from './routes/build-pack.$packId.index'
import { Route as CheckoutFakeHostedSessionIdRouteImport } from './routes/checkout.fake-hosted.$sessionId'
import { Route as BuildPackPackIdGeneratingRouteImport } from './routes/build-pack.$packId.generating'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluateRoute = EvaluateRouteImport.update({
  id: '/evaluate',
  path: '/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportEvaluationIdRoute = ReportEvaluationIdRouteImport.update({
  id: '/report/$evaluationId',
  path: '/report/$evaluationId',
  getParentRoute: () => rootRouteImport,
} as any)
const MaestroPackIdRoute = MaestroPackIdRouteImport.update({
  id: '/maestro/$packId',
  path: '/maestro/$packId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReportIdRoute = CheckoutReportIdRouteImport.update({
  id: '/checkout/$reportId',
  path: '/checkout/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildPackPackIdRoute = BuildPackPackIdRouteImport.update({
  id: '/build-pack/$packId',
  path: '/build-pack/$packId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkflowsRoute = WorkspaceWorkflowsRouteImport.update({
  id: '/_workspace/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSourcesRoute = WorkspaceSourcesRouteImport.update({
  id: '/_workspace/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/_workspace/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRunsRoute = WorkspaceRunsRouteImport.update({
  id: '/_workspace/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceOnboardingRoute = WorkspaceOnboardingRouteImport.update({
  id: '/_workspace/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceNotificationsRoute = WorkspaceNotificationsRouteImport.update({
  id: '/_workspace/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceLegalRoute = WorkspaceLegalRouteImport.update({
  id: '/_workspace/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIntegrationsRoute = WorkspaceIntegrationsRouteImport.update({
  id: '/_workspace/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceHealthRoute = WorkspaceHealthRouteImport.update({
  id: '/_workspace/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceDocumentsRoute = WorkspaceDocumentsRouteImport.update({
  id: '/_workspace/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceDataMapRoute = WorkspaceDataMapRouteImport.update({
  id: '/_workspace/data-map',
  path: '/data-map',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceDataLifecycleRoute = WorkspaceDataLifecycleRouteImport.update({
  id: '/_workspace/data-lifecycle',
  path: '/data-lifecycle',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceCapabilitiesRoute = WorkspaceCapabilitiesRouteImport.update({
  id: '/_workspace/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceBrainRoute = WorkspaceBrainRouteImport.update({
  id: '/_workspace/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceBillingRoute = WorkspaceBillingRouteImport.update({
  id: '/_workspace/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceApiRoute = WorkspaceApiRouteImport.update({
  id: '/_workspace/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceAnalyticsRoute = WorkspaceAnalyticsRouteImport.update({
  id: '/_workspace/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceAgentsRoute = WorkspaceAgentsRouteImport.update({
  id: '/_workspace/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceAdminRoute = WorkspaceAdminRouteImport.update({
  id: '/_workspace/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildPackPackIdIndexRoute = BuildPackPackIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuildPackPackIdRoute,
} as any)
const CheckoutFakeHostedSessionIdRoute =
  CheckoutFakeHostedSessionIdRouteImport.update({
    id: '/checkout/fake-hosted/$sessionId',
    path: '/checkout/fake-hosted/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BuildPackPackIdGeneratingRoute =
  BuildPackPackIdGeneratingRouteImport.update({
    id: '/generating',
    path: '/generating',
    getParentRoute: () => BuildPackPackIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/evaluate': typeof EvaluateRoute
  '/library': typeof LibraryRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin': typeof WorkspaceAdminRoute
  '/agents': typeof WorkspaceAgentsRoute
  '/analytics': typeof WorkspaceAnalyticsRoute
  '/api': typeof WorkspaceApiRoute
  '/billing': typeof WorkspaceBillingRoute
  '/brain': typeof WorkspaceBrainRoute
  '/capabilities': typeof WorkspaceCapabilitiesRoute
  '/data-lifecycle': typeof WorkspaceDataLifecycleRoute
  '/data-map': typeof WorkspaceDataMapRoute
  '/documents': typeof WorkspaceDocumentsRoute
  '/health': typeof WorkspaceHealthRoute
  '/integrations': typeof WorkspaceIntegrationsRoute
  '/legal': typeof WorkspaceLegalRoute
  '/notifications': typeof WorkspaceNotificationsRoute
  '/onboarding': typeof WorkspaceOnboardingRoute
  '/runs': typeof WorkspaceRunsRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/sources': typeof WorkspaceSourcesRoute
  '/workflows': typeof WorkspaceWorkflowsRoute
  '/build-pack/$packId': typeof BuildPackPackIdRouteWithChildren
  '/checkout/$reportId': typeof CheckoutReportIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/maestro/$packId': typeof MaestroPackIdRoute
  '/report/$evaluationId': typeof ReportEvaluationIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/build-pack/$packId/generating': typeof BuildPackPackIdGeneratingRoute
  '/checkout/fake-hosted/$sessionId': typeof CheckoutFakeHostedSessionIdRoute
  '/build-pack/$packId/': typeof BuildPackPackIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/evaluate': typeof EvaluateRoute
  '/library': typeof LibraryRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin': typeof WorkspaceAdminRoute
  '/agents': typeof WorkspaceAgentsRoute
  '/analytics': typeof WorkspaceAnalyticsRoute
  '/api': typeof WorkspaceApiRoute
  '/billing': typeof WorkspaceBillingRoute
  '/brain': typeof WorkspaceBrainRoute
  '/capabilities': typeof WorkspaceCapabilitiesRoute
  '/data-lifecycle': typeof WorkspaceDataLifecycleRoute
  '/data-map': typeof WorkspaceDataMapRoute
  '/documents': typeof WorkspaceDocumentsRoute
  '/health': typeof WorkspaceHealthRoute
  '/integrations': typeof WorkspaceIntegrationsRoute
  '/legal': typeof WorkspaceLegalRoute
  '/notifications': typeof WorkspaceNotificationsRoute
  '/onboarding': typeof WorkspaceOnboardingRoute
  '/runs': typeof WorkspaceRunsRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/sources': typeof WorkspaceSourcesRoute
  '/workflows': typeof WorkspaceWorkflowsRoute
  '/checkout/$reportId': typeof CheckoutReportIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/maestro/$packId': typeof MaestroPackIdRoute
  '/report/$evaluationId': typeof ReportEvaluationIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/build-pack/$packId/generating': typeof BuildPackPackIdGeneratingRoute
  '/checkout/fake-hosted/$sessionId': typeof CheckoutFakeHostedSessionIdRoute
  '/build-pack/$packId': typeof BuildPackPackIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/evaluate': typeof EvaluateRoute
  '/library': typeof LibraryRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/_workspace/admin': typeof WorkspaceAdminRoute
  '/_workspace/agents': typeof WorkspaceAgentsRoute
  '/_workspace/analytics': typeof WorkspaceAnalyticsRoute
  '/_workspace/api': typeof WorkspaceApiRoute
  '/_workspace/billing': typeof WorkspaceBillingRoute
  '/_workspace/brain': typeof WorkspaceBrainRoute
  '/_workspace/capabilities': typeof WorkspaceCapabilitiesRoute
  '/_workspace/data-lifecycle': typeof WorkspaceDataLifecycleRoute
  '/_workspace/data-map': typeof WorkspaceDataMapRoute
  '/_workspace/documents': typeof WorkspaceDocumentsRoute
  '/_workspace/health': typeof WorkspaceHealthRoute
  '/_workspace/integrations': typeof WorkspaceIntegrationsRoute
  '/_workspace/legal': typeof WorkspaceLegalRoute
  '/_workspace/notifications': typeof WorkspaceNotificationsRoute
  '/_workspace/onboarding': typeof WorkspaceOnboardingRoute
  '/_workspace/runs': typeof WorkspaceRunsRoute
  '/_workspace/settings': typeof WorkspaceSettingsRoute
  '/_workspace/sources': typeof WorkspaceSourcesRoute
  '/_workspace/workflows': typeof WorkspaceWorkflowsRoute
  '/build-pack/$packId': typeof BuildPackPackIdRouteWithChildren
  '/checkout/$reportId': typeof CheckoutReportIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/maestro/$packId': typeof MaestroPackIdRoute
  '/report/$evaluationId': typeof ReportEvaluationIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/build-pack/$packId/generating': typeof BuildPackPackIdGeneratingRoute
  '/checkout/fake-hosted/$sessionId': typeof CheckoutFakeHostedSessionIdRoute
  '/build-pack/$packId/': typeof BuildPackPackIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/evaluate'
    | '/library'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/admin'
    | '/agents'
    | '/analytics'
    | '/api'
    | '/billing'
    | '/brain'
    | '/capabilities'
    | '/data-lifecycle'
    | '/data-map'
    | '/documents'
    | '/health'
    | '/integrations'
    | '/legal'
    | '/notifications'
    | '/onboarding'
    | '/runs'
    | '/settings'
    | '/sources'
    | '/workflows'
    | '/build-pack/$packId'
    | '/checkout/$reportId'
    | '/checkout/return'
    | '/maestro/$packId'
    | '/report/$evaluationId'
    | '/share/$token'
    | '/build-pack/$packId/generating'
    | '/checkout/fake-hosted/$sessionId'
    | '/build-pack/$packId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/evaluate'
    | '/library'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/admin'
    | '/agents'
    | '/analytics'
    | '/api'
    | '/billing'
    | '/brain'
    | '/capabilities'
    | '/data-lifecycle'
    | '/data-map'
    | '/documents'
    | '/health'
    | '/integrations'
    | '/legal'
    | '/notifications'
    | '/onboarding'
    | '/runs'
    | '/settings'
    | '/sources'
    | '/workflows'
    | '/checkout/$reportId'
    | '/checkout/return'
    | '/maestro/$packId'
    | '/report/$evaluationId'
    | '/share/$token'
    | '/build-pack/$packId/generating'
    | '/checkout/fake-hosted/$sessionId'
    | '/build-pack/$packId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/evaluate'
    | '/library'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/_workspace/admin'
    | '/_workspace/agents'
    | '/_workspace/analytics'
    | '/_workspace/api'
    | '/_workspace/billing'
    | '/_workspace/brain'
    | '/_workspace/capabilities'
    | '/_workspace/data-lifecycle'
    | '/_workspace/data-map'
    | '/_workspace/documents'
    | '/_workspace/health'
    | '/_workspace/integrations'
    | '/_workspace/legal'
    | '/_workspace/notifications'
    | '/_workspace/onboarding'
    | '/_workspace/runs'
    | '/_workspace/settings'
    | '/_workspace/sources'
    | '/_workspace/workflows'
    | '/build-pack/$packId'
    | '/checkout/$reportId'
    | '/checkout/return'
    | '/maestro/$packId'
    | '/report/$evaluationId'
    | '/share/$token'
    | '/build-pack/$packId/generating'
    | '/checkout/fake-hosted/$sessionId'
    | '/build-pack/$packId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EvaluateRoute: typeof EvaluateRoute
  LibraryRoute: typeof LibraryRoute
  PrivacyRoute: typeof PrivacyRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  WorkspaceAdminRoute: typeof WorkspaceAdminRoute
  WorkspaceAgentsRoute: typeof WorkspaceAgentsRoute
  WorkspaceAnalyticsRoute: typeof WorkspaceAnalyticsRoute
  WorkspaceApiRoute: typeof WorkspaceApiRoute
  WorkspaceBillingRoute: typeof WorkspaceBillingRoute
  WorkspaceBrainRoute: typeof WorkspaceBrainRoute
  WorkspaceCapabilitiesRoute: typeof WorkspaceCapabilitiesRoute
  WorkspaceDataLifecycleRoute: typeof WorkspaceDataLifecycleRoute
  WorkspaceDataMapRoute: typeof WorkspaceDataMapRoute
  WorkspaceDocumentsRoute: typeof WorkspaceDocumentsRoute
  WorkspaceHealthRoute: typeof WorkspaceHealthRoute
  WorkspaceIntegrationsRoute: typeof WorkspaceIntegrationsRoute
  WorkspaceLegalRoute: typeof WorkspaceLegalRoute
  WorkspaceNotificationsRoute: typeof WorkspaceNotificationsRoute
  WorkspaceOnboardingRoute: typeof WorkspaceOnboardingRoute
  WorkspaceRunsRoute: typeof WorkspaceRunsRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceSourcesRoute: typeof WorkspaceSourcesRoute
  WorkspaceWorkflowsRoute: typeof WorkspaceWorkflowsRoute
  BuildPackPackIdRoute: typeof BuildPackPackIdRouteWithChildren
  CheckoutReportIdRoute: typeof CheckoutReportIdRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  MaestroPackIdRoute: typeof MaestroPackIdRoute
  ReportEvaluationIdRoute: typeof ReportEvaluationIdRoute
  ShareTokenRoute: typeof ShareTokenRoute
  CheckoutFakeHostedSessionIdRoute: typeof CheckoutFakeHostedSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluate': {
      id: '/evaluate'
      path: '/evaluate'
      fullPath: '/evaluate'
      preLoaderRoute: typeof EvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$evaluationId': {
      id: '/report/$evaluationId'
      path: '/report/$evaluationId'
      fullPath: '/report/$evaluationId'
      preLoaderRoute: typeof ReportEvaluationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maestro/$packId': {
      id: '/maestro/$packId'
      path: '/maestro/$packId'
      fullPath: '/maestro/$packId'
      preLoaderRoute: typeof MaestroPackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$reportId': {
      id: '/checkout/$reportId'
      path: '/checkout/$reportId'
      fullPath: '/checkout/$reportId'
      preLoaderRoute: typeof CheckoutReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-pack/$packId': {
      id: '/build-pack/$packId'
      path: '/build-pack/$packId'
      fullPath: '/build-pack/$packId'
      preLoaderRoute: typeof BuildPackPackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/workflows': {
      id: '/_workspace/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkspaceWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/sources': {
      id: '/_workspace/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof WorkspaceSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/runs': {
      id: '/_workspace/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof WorkspaceRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/onboarding': {
      id: '/_workspace/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof WorkspaceOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/notifications': {
      id: '/_workspace/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof WorkspaceNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/legal': {
      id: '/_workspace/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof WorkspaceLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/integrations': {
      id: '/_workspace/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof WorkspaceIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/health': {
      id: '/_workspace/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof WorkspaceHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/documents': {
      id: '/_workspace/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof WorkspaceDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/data-map': {
      id: '/_workspace/data-map'
      path: '/data-map'
      fullPath: '/data-map'
      preLoaderRoute: typeof WorkspaceDataMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/data-lifecycle': {
      id: '/_workspace/data-lifecycle'
      path: '/data-lifecycle'
      fullPath: '/data-lifecycle'
      preLoaderRoute: typeof WorkspaceDataLifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/capabilities': {
      id: '/_workspace/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof WorkspaceCapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/brain': {
      id: '/_workspace/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof WorkspaceBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/billing': {
      id: '/_workspace/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof WorkspaceBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/api': {
      id: '/_workspace/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof WorkspaceApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/analytics': {
      id: '/_workspace/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof WorkspaceAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/agents': {
      id: '/_workspace/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof WorkspaceAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/admin': {
      id: '/_workspace/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof WorkspaceAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-pack/$packId/': {
      id: '/build-pack/$packId/'
      path: '/'
      fullPath: '/build-pack/$packId/'
      preLoaderRoute: typeof BuildPackPackIdIndexRouteImport
      parentRoute: typeof BuildPackPackIdRoute
    }
    '/checkout/fake-hosted/$sessionId': {
      id: '/checkout/fake-hosted/$sessionId'
      path: '/checkout/fake-hosted/$sessionId'
      fullPath: '/checkout/fake-hosted/$sessionId'
      preLoaderRoute: typeof CheckoutFakeHostedSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-pack/$packId/generating': {
      id: '/build-pack/$packId/generating'
      path: '/generating'
      fullPath: '/build-pack/$packId/generating'
      preLoaderRoute: typeof BuildPackPackIdGeneratingRouteImport
      parentRoute: typeof BuildPackPackIdRoute
    }
  }
}

interface BuildPackPackIdRouteChildren {
  BuildPackPackIdGeneratingRoute: typeof BuildPackPackIdGeneratingRoute
  BuildPackPackIdIndexRoute: typeof BuildPackPackIdIndexRoute
}

const BuildPackPackIdRouteChildren: BuildPackPackIdRouteChildren = {
  BuildPackPackIdGeneratingRoute: BuildPackPackIdGeneratingRoute,
  BuildPackPackIdIndexRoute: BuildPackPackIdIndexRoute,
}

const BuildPackPackIdRouteWithChildren = BuildPackPackIdRoute._addFileChildren(
  BuildPackPackIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EvaluateRoute: EvaluateRoute,
  LibraryRoute: LibraryRoute,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  WorkspaceAdminRoute: WorkspaceAdminRoute,
  WorkspaceAgentsRoute: WorkspaceAgentsRoute,
  WorkspaceAnalyticsRoute: WorkspaceAnalyticsRoute,
  WorkspaceApiRoute: WorkspaceApiRoute,
  WorkspaceBillingRoute: WorkspaceBillingRoute,
  WorkspaceBrainRoute: WorkspaceBrainRoute,
  WorkspaceCapabilitiesRoute: WorkspaceCapabilitiesRoute,
  WorkspaceDataLifecycleRoute: WorkspaceDataLifecycleRoute,
  WorkspaceDataMapRoute: WorkspaceDataMapRoute,
  WorkspaceDocumentsRoute: WorkspaceDocumentsRoute,
  WorkspaceHealthRoute: WorkspaceHealthRoute,
  WorkspaceIntegrationsRoute: WorkspaceIntegrationsRoute,
  WorkspaceLegalRoute: WorkspaceLegalRoute,
  WorkspaceNotificationsRoute: WorkspaceNotificationsRoute,
  WorkspaceOnboardingRoute: WorkspaceOnboardingRoute,
  WorkspaceRunsRoute: WorkspaceRunsRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceSourcesRoute: WorkspaceSourcesRoute,
  WorkspaceWorkflowsRoute: WorkspaceWorkflowsRoute,
  BuildPackPackIdRoute: BuildPackPackIdRouteWithChildren,
  CheckoutReportIdRoute: CheckoutReportIdRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  MaestroPackIdRoute: MaestroPackIdRoute,
  ReportEvaluationIdRoute: ReportEvaluationIdRoute,
  ShareTokenRoute: ShareTokenRoute,
  CheckoutFakeHostedSessionIdRoute: CheckoutFakeHostedSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
