/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWorkspaceRouteImport } from './routes/_app/$workspace'
import { Route as AppAcceptInviteRouteImport } from './routes/_app/accept-invite'
import { Route as AppGettingStartedRouteImport } from './routes/_app/getting-started'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AppWorkspaceDashboardRouteImport } from './routes/_app/$workspace/_dashboard'
import { Route as AppWorkspaceSettingsRouteImport } from './routes/_app/$workspace/settings'
import { Route as AppAcceptInviteTokenRouteImport } from './routes/_app/accept-invite/$token'
import { Route as AppGettingStartedIndexRouteImport } from './routes/_app/getting-started/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth/sign-in'
import { Route as ApiAuthSignUpRouteImport } from './routes/api/auth/sign-up'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as AppWorkspaceDashboardIndexRouteImport } from './routes/_app/$workspace/_dashboard/index'
import { Route as AppWorkspaceDashboardInboxRouteImport } from './routes/_app/$workspace/_dashboard/inbox'
import { Route as AppWorkspaceDashboardKanbanRouteImport } from './routes/_app/$workspace/_dashboard/kanban'
import { Route as AppWorkspaceDashboardSearchRouteImport } from './routes/_app/$workspace/_dashboard/search'
import { Route as AppWorkspaceDashboardShowcaseRouteImport } from './routes/_app/$workspace/_dashboard/showcase'
import { Route as AppWorkspaceSettingsIndexRouteImport } from './routes/_app/$workspace/settings/index'
import { Route as AppWorkspaceSettingsBillingRouteImport } from './routes/_app/$workspace/settings/billing'
import { Route as AppWorkspaceSettingsMembersRouteImport } from './routes/_app/$workspace/settings/members'
import { Route as AppWorkspaceSettingsPlansRouteImport } from './routes/_app/$workspace/settings/plans'
import { Route as AppWorkspaceSettingsTagsRouteImport } from './routes/_app/$workspace/settings/tags'
import { Route as AppWorkspaceSettingsWorkspaceRouteImport } from './routes/_app/$workspace/settings/workspace'
import { Route as AppWorkspaceDashboardContactsIndexRouteImport } from './routes/_app/$workspace/_dashboard/contacts/index'
import { Route as AppWorkspaceDashboardContactsTypeRouteImport } from './routes/_app/$workspace/_dashboard/contacts/$type'
import { Route as AppWorkspaceDashboardInboxIdRouteImport } from './routes/_app/$workspace/_dashboard/inbox/$id'
import { Route as AppWorkspaceDashboardTagTagRouteImport } from './routes/_app/$workspace/_dashboard/tag/$tag'
import { Route as AppWorkspaceSettingsAccountIndexRouteImport } from './routes/_app/$workspace/settings/account/index'
import { Route as AppWorkspaceSettingsAccountProfileRouteImport } from './routes/_app/$workspace/settings/account/profile'
import { Route as AppWorkspaceSettingsAccountSecurityRouteImport } from './routes/_app/$workspace/settings/account/security'
import { Route as AppWorkspaceDashboardContactsViewIdRouteImport } from './routes/_app/$workspace/_dashboard/contacts/view/$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/$workspace',
  path: '/$workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppAcceptInviteRoute = AppAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => AppRoute,
} as any)
const AppGettingStartedRoute = AppGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AppWorkspaceDashboardRoute = AppWorkspaceDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceSettingsRoute = AppWorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppAcceptInviteTokenRoute = AppAcceptInviteTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => AppAcceptInviteRoute,
} as any)
const AppGettingStartedIndexRoute = AppGettingStartedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGettingStartedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignUpRoute = ApiAuthSignUpRouteImport.update({
  id: '/api/auth/sign-up',
  path: '/api/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceDashboardIndexRoute =
  AppWorkspaceDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceDashboardRoute,
  } as any)
const AppWorkspaceDashboardInboxRoute =
  AppWorkspaceDashboardInboxRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => AppWorkspaceDashboardRoute,
  } as any)
const AppWorkspaceDashboardKanbanRoute =
  AppWorkspaceDashboardKanbanRouteImport.update({
    id: '/kanban',
    path: '/kanban',
    getParentRoute: () => AppWorkspaceDashboardRoute,
  } as any)
const AppWorkspaceDashboardSearchRoute =
  AppWorkspaceDashboardSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => AppWorkspaceDashboardRoute,
  } as any)
const AppWorkspaceDashboardShowcaseRoute =
  AppWorkspaceDashboardShowcaseRouteImport.update({
    id: '/showcase',
    path: '/showcase',
    getParentRoute: () => AppWorkspaceDashboardRoute,
  } as any)
const AppWorkspaceSettingsIndexRoute =
  AppWorkspaceSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceSettingsRoute,
  } as any)
const AppWorkspaceSettingsBillingRoute =
  AppWorkspaceSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AppWorkspaceSettingsRoute,
  } as any)
const AppWorkspaceSettingsMembersRoute =
  AppWorkspaceSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppWorkspaceSettingsRoute,
  } as any)
const AppWorkspaceSettingsPlansRoute =
  AppWorkspaceSettingsPlansRouteImport.update({
    id: '/plans',
    path: '/plans',
    getParentRoute: () => AppWorkspaceSettingsRoute,
  } as any)
const AppWorkspaceSettingsTagsRoute =
  AppWorkspaceSettingsTagsRouteImport.update({
    id: '/tags',
    path: '/tags',
    getParentRoute: () => AppWorkspaceSettingsRoute,
  } as any)
const AppWorkspaceSettingsWorkspaceRoute =
  AppWorkspaceSettingsWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => AppWorkspaceSettingsRoute,
  } as any)
const AppWorkspaceDashboardContactsIndexRoute =
  AppWorkspaceDashboardContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => AppWorkspaceDashboardRoute,
  } as any)
const AppWorkspaceDashboardContactsTypeRoute =
  AppWorkspaceDashboardContactsTypeRouteImport.update({
    id: '/contacts/$type',
    path: '/contacts/$type',
    getParentRoute: () => AppWorkspaceDashboardRoute,
  } as any)
const AppWorkspaceDashboardInboxIdRoute =
  AppWorkspaceDashboardInboxIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppWorkspaceDashboardInboxRoute,
  } as any)
const AppWorkspaceDashboardTagTagRoute =
  AppWorkspaceDashboardTagTagRouteImport.update({
    id: '/tag/$tag',
    path: '/tag/$tag',
    getParentRoute: () => AppWorkspaceDashboardRoute,
  } as any)
const AppWorkspaceSettingsAccountIndexRoute =
  AppWorkspaceSettingsAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AppWorkspaceSettingsRoute,
  } as any)
const AppWorkspaceSettingsAccountProfileRoute =
  AppWorkspaceSettingsAccountProfileRouteImport.update({
    id: '/account/profile',
    path: '/account/profile',
    getParentRoute: () => AppWorkspaceSettingsRoute,
  } as any)
const AppWorkspaceSettingsAccountSecurityRoute =
  AppWorkspaceSettingsAccountSecurityRouteImport.update({
    id: '/account/security',
    path: '/account/security',
    getParentRoute: () => AppWorkspaceSettingsRoute,
  } as any)
const AppWorkspaceDashboardContactsViewIdRoute =
  AppWorkspaceDashboardContactsViewIdRouteImport.update({
    id: '/contacts/view/$id',
    path: '/contacts/view/$id',
    getParentRoute: () => AppWorkspaceDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/$workspace': typeof AppWorkspaceRouteWithChildren
  '/accept-invite': typeof AppAcceptInviteRouteWithChildren
  '/getting-started': typeof AppGettingStartedRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/$workspace/settings': typeof AppWorkspaceSettingsRouteWithChildren
  '/accept-invite/$token': typeof AppAcceptInviteTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/getting-started/': typeof AppGettingStartedIndexRoute
  '/$workspace/inbox': typeof AppWorkspaceDashboardInboxRouteWithChildren
  '/$workspace/kanban': typeof AppWorkspaceDashboardKanbanRoute
  '/$workspace/search': typeof AppWorkspaceDashboardSearchRoute
  '/$workspace/showcase': typeof AppWorkspaceDashboardShowcaseRoute
  '/$workspace/settings/billing': typeof AppWorkspaceSettingsBillingRoute
  '/$workspace/settings/members': typeof AppWorkspaceSettingsMembersRoute
  '/$workspace/settings/plans': typeof AppWorkspaceSettingsPlansRoute
  '/$workspace/settings/tags': typeof AppWorkspaceSettingsTagsRoute
  '/$workspace/settings/workspace': typeof AppWorkspaceSettingsWorkspaceRoute
  '/$workspace/': typeof AppWorkspaceDashboardIndexRoute
  '/$workspace/settings/': typeof AppWorkspaceSettingsIndexRoute
  '/$workspace/contacts/$type': typeof AppWorkspaceDashboardContactsTypeRoute
  '/$workspace/inbox/$id': typeof AppWorkspaceDashboardInboxIdRoute
  '/$workspace/tag/$tag': typeof AppWorkspaceDashboardTagTagRoute
  '/$workspace/settings/account/profile': typeof AppWorkspaceSettingsAccountProfileRoute
  '/$workspace/settings/account/security': typeof AppWorkspaceSettingsAccountSecurityRoute
  '/$workspace/contacts/': typeof AppWorkspaceDashboardContactsIndexRoute
  '/$workspace/settings/account/': typeof AppWorkspaceSettingsAccountIndexRoute
  '/$workspace/contacts/view/$id': typeof AppWorkspaceDashboardContactsViewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/$workspace': typeof AppWorkspaceDashboardIndexRoute
  '/accept-invite': typeof AppAcceptInviteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/accept-invite/$token': typeof AppAcceptInviteTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/getting-started': typeof AppGettingStartedIndexRoute
  '/$workspace/inbox': typeof AppWorkspaceDashboardInboxRouteWithChildren
  '/$workspace/kanban': typeof AppWorkspaceDashboardKanbanRoute
  '/$workspace/search': typeof AppWorkspaceDashboardSearchRoute
  '/$workspace/showcase': typeof AppWorkspaceDashboardShowcaseRoute
  '/$workspace/settings/billing': typeof AppWorkspaceSettingsBillingRoute
  '/$workspace/settings/members': typeof AppWorkspaceSettingsMembersRoute
  '/$workspace/settings/plans': typeof AppWorkspaceSettingsPlansRoute
  '/$workspace/settings/tags': typeof AppWorkspaceSettingsTagsRoute
  '/$workspace/settings/workspace': typeof AppWorkspaceSettingsWorkspaceRoute
  '/$workspace/settings': typeof AppWorkspaceSettingsIndexRoute
  '/$workspace/contacts/$type': typeof AppWorkspaceDashboardContactsTypeRoute
  '/$workspace/inbox/$id': typeof AppWorkspaceDashboardInboxIdRoute
  '/$workspace/tag/$tag': typeof AppWorkspaceDashboardTagTagRoute
  '/$workspace/settings/account/profile': typeof AppWorkspaceSettingsAccountProfileRoute
  '/$workspace/settings/account/security': typeof AppWorkspaceSettingsAccountSecurityRoute
  '/$workspace/contacts': typeof AppWorkspaceDashboardContactsIndexRoute
  '/$workspace/settings/account': typeof AppWorkspaceSettingsAccountIndexRoute
  '/$workspace/contacts/view/$id': typeof AppWorkspaceDashboardContactsViewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/$workspace': typeof AppWorkspaceRouteWithChildren
  '/_app/accept-invite': typeof AppAcceptInviteRouteWithChildren
  '/_app/getting-started': typeof AppGettingStartedRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/$workspace/_dashboard': typeof AppWorkspaceDashboardRouteWithChildren
  '/_app/$workspace/settings': typeof AppWorkspaceSettingsRouteWithChildren
  '/_app/accept-invite/$token': typeof AppAcceptInviteTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/_app/getting-started/': typeof AppGettingStartedIndexRoute
  '/_app/$workspace/_dashboard/inbox': typeof AppWorkspaceDashboardInboxRouteWithChildren
  '/_app/$workspace/_dashboard/kanban': typeof AppWorkspaceDashboardKanbanRoute
  '/_app/$workspace/_dashboard/search': typeof AppWorkspaceDashboardSearchRoute
  '/_app/$workspace/_dashboard/showcase': typeof AppWorkspaceDashboardShowcaseRoute
  '/_app/$workspace/settings/billing': typeof AppWorkspaceSettingsBillingRoute
  '/_app/$workspace/settings/members': typeof AppWorkspaceSettingsMembersRoute
  '/_app/$workspace/settings/plans': typeof AppWorkspaceSettingsPlansRoute
  '/_app/$workspace/settings/tags': typeof AppWorkspaceSettingsTagsRoute
  '/_app/$workspace/settings/workspace': typeof AppWorkspaceSettingsWorkspaceRoute
  '/_app/$workspace/_dashboard/': typeof AppWorkspaceDashboardIndexRoute
  '/_app/$workspace/settings/': typeof AppWorkspaceSettingsIndexRoute
  '/_app/$workspace/_dashboard/contacts/$type': typeof AppWorkspaceDashboardContactsTypeRoute
  '/_app/$workspace/_dashboard/inbox/$id': typeof AppWorkspaceDashboardInboxIdRoute
  '/_app/$workspace/_dashboard/tag/$tag': typeof AppWorkspaceDashboardTagTagRoute
  '/_app/$workspace/settings/account/profile': typeof AppWorkspaceSettingsAccountProfileRoute
  '/_app/$workspace/settings/account/security': typeof AppWorkspaceSettingsAccountSecurityRoute
  '/_app/$workspace/_dashboard/contacts/': typeof AppWorkspaceDashboardContactsIndexRoute
  '/_app/$workspace/settings/account/': typeof AppWorkspaceSettingsAccountIndexRoute
  '/_app/$workspace/_dashboard/contacts/view/$id': typeof AppWorkspaceDashboardContactsViewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$workspace'
    | '/accept-invite'
    | '/getting-started'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/$workspace/settings'
    | '/accept-invite/$token'
    | '/api/auth/$'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/auth/sign-up'
    | '/api/trpc/$'
    | '/api/webhooks/stripe'
    | '/getting-started/'
    | '/$workspace/inbox'
    | '/$workspace/kanban'
    | '/$workspace/search'
    | '/$workspace/showcase'
    | '/$workspace/settings/billing'
    | '/$workspace/settings/members'
    | '/$workspace/settings/plans'
    | '/$workspace/settings/tags'
    | '/$workspace/settings/workspace'
    | '/$workspace/'
    | '/$workspace/settings/'
    | '/$workspace/contacts/$type'
    | '/$workspace/inbox/$id'
    | '/$workspace/tag/$tag'
    | '/$workspace/settings/account/profile'
    | '/$workspace/settings/account/security'
    | '/$workspace/contacts/'
    | '/$workspace/settings/account/'
    | '/$workspace/contacts/view/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$workspace'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/accept-invite/$token'
    | '/api/auth/$'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/auth/sign-up'
    | '/api/trpc/$'
    | '/api/webhooks/stripe'
    | '/getting-started'
    | '/$workspace/inbox'
    | '/$workspace/kanban'
    | '/$workspace/search'
    | '/$workspace/showcase'
    | '/$workspace/settings/billing'
    | '/$workspace/settings/members'
    | '/$workspace/settings/plans'
    | '/$workspace/settings/tags'
    | '/$workspace/settings/workspace'
    | '/$workspace/settings'
    | '/$workspace/contacts/$type'
    | '/$workspace/inbox/$id'
    | '/$workspace/tag/$tag'
    | '/$workspace/settings/account/profile'
    | '/$workspace/settings/account/security'
    | '/$workspace/contacts'
    | '/$workspace/settings/account'
    | '/$workspace/contacts/view/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/$workspace'
    | '/_app/accept-invite'
    | '/_app/getting-started'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/_app/'
    | '/_app/$workspace/_dashboard'
    | '/_app/$workspace/settings'
    | '/_app/accept-invite/$token'
    | '/api/auth/$'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/auth/sign-up'
    | '/api/trpc/$'
    | '/api/webhooks/stripe'
    | '/_app/getting-started/'
    | '/_app/$workspace/_dashboard/inbox'
    | '/_app/$workspace/_dashboard/kanban'
    | '/_app/$workspace/_dashboard/search'
    | '/_app/$workspace/_dashboard/showcase'
    | '/_app/$workspace/settings/billing'
    | '/_app/$workspace/settings/members'
    | '/_app/$workspace/settings/plans'
    | '/_app/$workspace/settings/tags'
    | '/_app/$workspace/settings/workspace'
    | '/_app/$workspace/_dashboard/'
    | '/_app/$workspace/settings/'
    | '/_app/$workspace/_dashboard/contacts/$type'
    | '/_app/$workspace/_dashboard/inbox/$id'
    | '/_app/$workspace/_dashboard/tag/$tag'
    | '/_app/$workspace/settings/account/profile'
    | '/_app/$workspace/settings/account/security'
    | '/_app/$workspace/_dashboard/contacts/'
    | '/_app/$workspace/settings/account/'
    | '/_app/$workspace/_dashboard/contacts/view/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
  ApiAuthSignUpRoute: typeof ApiAuthSignUpRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$workspace': {
      id: '/_app/$workspace'
      path: '/$workspace'
      fullPath: '/$workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accept-invite': {
      id: '/_app/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AppAcceptInviteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/getting-started': {
      id: '/_app/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof AppGettingStartedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/$workspace/_dashboard': {
      id: '/_app/$workspace/_dashboard'
      path: ''
      fullPath: '/$workspace'
      preLoaderRoute: typeof AppWorkspaceDashboardRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/$workspace/settings': {
      id: '/_app/$workspace/settings'
      path: '/settings'
      fullPath: '/$workspace/settings'
      preLoaderRoute: typeof AppWorkspaceSettingsRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/accept-invite/$token': {
      id: '/_app/accept-invite/$token'
      path: '/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof AppAcceptInviteTokenRouteImport
      parentRoute: typeof AppAcceptInviteRoute
    }
    '/_app/getting-started/': {
      id: '/_app/getting-started/'
      path: '/'
      fullPath: '/getting-started/'
      preLoaderRoute: typeof AppGettingStartedIndexRouteImport
      parentRoute: typeof AppGettingStartedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-up': {
      id: '/api/auth/sign-up'
      path: '/api/auth/sign-up'
      fullPath: '/api/auth/sign-up'
      preLoaderRoute: typeof ApiAuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$workspace/_dashboard/': {
      id: '/_app/$workspace/_dashboard/'
      path: '/'
      fullPath: '/$workspace/'
      preLoaderRoute: typeof AppWorkspaceDashboardIndexRouteImport
      parentRoute: typeof AppWorkspaceDashboardRoute
    }
    '/_app/$workspace/_dashboard/inbox': {
      id: '/_app/$workspace/_dashboard/inbox'
      path: '/inbox'
      fullPath: '/$workspace/inbox'
      preLoaderRoute: typeof AppWorkspaceDashboardInboxRouteImport
      parentRoute: typeof AppWorkspaceDashboardRoute
    }
    '/_app/$workspace/_dashboard/kanban': {
      id: '/_app/$workspace/_dashboard/kanban'
      path: '/kanban'
      fullPath: '/$workspace/kanban'
      preLoaderRoute: typeof AppWorkspaceDashboardKanbanRouteImport
      parentRoute: typeof AppWorkspaceDashboardRoute
    }
    '/_app/$workspace/_dashboard/search': {
      id: '/_app/$workspace/_dashboard/search'
      path: '/search'
      fullPath: '/$workspace/search'
      preLoaderRoute: typeof AppWorkspaceDashboardSearchRouteImport
      parentRoute: typeof AppWorkspaceDashboardRoute
    }
    '/_app/$workspace/_dashboard/showcase': {
      id: '/_app/$workspace/_dashboard/showcase'
      path: '/showcase'
      fullPath: '/$workspace/showcase'
      preLoaderRoute: typeof AppWorkspaceDashboardShowcaseRouteImport
      parentRoute: typeof AppWorkspaceDashboardRoute
    }
    '/_app/$workspace/settings/': {
      id: '/_app/$workspace/settings/'
      path: '/'
      fullPath: '/$workspace/settings/'
      preLoaderRoute: typeof AppWorkspaceSettingsIndexRouteImport
      parentRoute: typeof AppWorkspaceSettingsRoute
    }
    '/_app/$workspace/settings/billing': {
      id: '/_app/$workspace/settings/billing'
      path: '/billing'
      fullPath: '/$workspace/settings/billing'
      preLoaderRoute: typeof AppWorkspaceSettingsBillingRouteImport
      parentRoute: typeof AppWorkspaceSettingsRoute
    }
    '/_app/$workspace/settings/members': {
      id: '/_app/$workspace/settings/members'
      path: '/members'
      fullPath: '/$workspace/settings/members'
      preLoaderRoute: typeof AppWorkspaceSettingsMembersRouteImport
      parentRoute: typeof AppWorkspaceSettingsRoute
    }
    '/_app/$workspace/settings/plans': {
      id: '/_app/$workspace/settings/plans'
      path: '/plans'
      fullPath: '/$workspace/settings/plans'
      preLoaderRoute: typeof AppWorkspaceSettingsPlansRouteImport
      parentRoute: typeof AppWorkspaceSettingsRoute
    }
    '/_app/$workspace/settings/tags': {
      id: '/_app/$workspace/settings/tags'
      path: '/tags'
      fullPath: '/$workspace/settings/tags'
      preLoaderRoute: typeof AppWorkspaceSettingsTagsRouteImport
      parentRoute: typeof AppWorkspaceSettingsRoute
    }
    '/_app/$workspace/settings/workspace': {
      id: '/_app/$workspace/settings/workspace'
      path: '/workspace'
      fullPath: '/$workspace/settings/workspace'
      preLoaderRoute: typeof AppWorkspaceSettingsWorkspaceRouteImport
      parentRoute: typeof AppWorkspaceSettingsRoute
    }
    '/_app/$workspace/_dashboard/contacts/': {
      id: '/_app/$workspace/_dashboard/contacts/'
      path: '/contacts'
      fullPath: '/$workspace/contacts/'
      preLoaderRoute: typeof AppWorkspaceDashboardContactsIndexRouteImport
      parentRoute: typeof AppWorkspaceDashboardRoute
    }
    '/_app/$workspace/_dashboard/contacts/$type': {
      id: '/_app/$workspace/_dashboard/contacts/$type'
      path: '/contacts/$type'
      fullPath: '/$workspace/contacts/$type'
      preLoaderRoute: typeof AppWorkspaceDashboardContactsTypeRouteImport
      parentRoute: typeof AppWorkspaceDashboardRoute
    }
    '/_app/$workspace/_dashboard/inbox/$id': {
      id: '/_app/$workspace/_dashboard/inbox/$id'
      path: '/$id'
      fullPath: '/$workspace/inbox/$id'
      preLoaderRoute: typeof AppWorkspaceDashboardInboxIdRouteImport
      parentRoute: typeof AppWorkspaceDashboardInboxRoute
    }
    '/_app/$workspace/_dashboard/tag/$tag': {
      id: '/_app/$workspace/_dashboard/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/$workspace/tag/$tag'
      preLoaderRoute: typeof AppWorkspaceDashboardTagTagRouteImport
      parentRoute: typeof AppWorkspaceDashboardRoute
    }
    '/_app/$workspace/settings/account/': {
      id: '/_app/$workspace/settings/account/'
      path: '/account'
      fullPath: '/$workspace/settings/account/'
      preLoaderRoute: typeof AppWorkspaceSettingsAccountIndexRouteImport
      parentRoute: typeof AppWorkspaceSettingsRoute
    }
    '/_app/$workspace/settings/account/profile': {
      id: '/_app/$workspace/settings/account/profile'
      path: '/account/profile'
      fullPath: '/$workspace/settings/account/profile'
      preLoaderRoute: typeof AppWorkspaceSettingsAccountProfileRouteImport
      parentRoute: typeof AppWorkspaceSettingsRoute
    }
    '/_app/$workspace/settings/account/security': {
      id: '/_app/$workspace/settings/account/security'
      path: '/account/security'
      fullPath: '/$workspace/settings/account/security'
      preLoaderRoute: typeof AppWorkspaceSettingsAccountSecurityRouteImport
      parentRoute: typeof AppWorkspaceSettingsRoute
    }
    '/_app/$workspace/_dashboard/contacts/view/$id': {
      id: '/_app/$workspace/_dashboard/contacts/view/$id'
      path: '/contacts/view/$id'
      fullPath: '/$workspace/contacts/view/$id'
      preLoaderRoute: typeof AppWorkspaceDashboardContactsViewIdRouteImport
      parentRoute: typeof AppWorkspaceDashboardRoute
    }
  }
}

interface AppWorkspaceDashboardInboxRouteChildren {
  AppWorkspaceDashboardInboxIdRoute: typeof AppWorkspaceDashboardInboxIdRoute
}

const AppWorkspaceDashboardInboxRouteChildren: AppWorkspaceDashboardInboxRouteChildren =
  {
    AppWorkspaceDashboardInboxIdRoute: AppWorkspaceDashboardInboxIdRoute,
  }

const AppWorkspaceDashboardInboxRouteWithChildren =
  AppWorkspaceDashboardInboxRoute._addFileChildren(
    AppWorkspaceDashboardInboxRouteChildren,
  )

interface AppWorkspaceDashboardRouteChildren {
  AppWorkspaceDashboardInboxRoute: typeof AppWorkspaceDashboardInboxRouteWithChildren
  AppWorkspaceDashboardKanbanRoute: typeof AppWorkspaceDashboardKanbanRoute
  AppWorkspaceDashboardSearchRoute: typeof AppWorkspaceDashboardSearchRoute
  AppWorkspaceDashboardShowcaseRoute: typeof AppWorkspaceDashboardShowcaseRoute
  AppWorkspaceDashboardIndexRoute: typeof AppWorkspaceDashboardIndexRoute
  AppWorkspaceDashboardContactsTypeRoute: typeof AppWorkspaceDashboardContactsTypeRoute
  AppWorkspaceDashboardTagTagRoute: typeof AppWorkspaceDashboardTagTagRoute
  AppWorkspaceDashboardContactsIndexRoute: typeof AppWorkspaceDashboardContactsIndexRoute
  AppWorkspaceDashboardContactsViewIdRoute: typeof AppWorkspaceDashboardContactsViewIdRoute
}

const AppWorkspaceDashboardRouteChildren: AppWorkspaceDashboardRouteChildren = {
  AppWorkspaceDashboardInboxRoute: AppWorkspaceDashboardInboxRouteWithChildren,
  AppWorkspaceDashboardKanbanRoute: AppWorkspaceDashboardKanbanRoute,
  AppWorkspaceDashboardSearchRoute: AppWorkspaceDashboardSearchRoute,
  AppWorkspaceDashboardShowcaseRoute: AppWorkspaceDashboardShowcaseRoute,
  AppWorkspaceDashboardIndexRoute: AppWorkspaceDashboardIndexRoute,
  AppWorkspaceDashboardContactsTypeRoute:
    AppWorkspaceDashboardContactsTypeRoute,
  AppWorkspaceDashboardTagTagRoute: AppWorkspaceDashboardTagTagRoute,
  AppWorkspaceDashboardContactsIndexRoute:
    AppWorkspaceDashboardContactsIndexRoute,
  AppWorkspaceDashboardContactsViewIdRoute:
    AppWorkspaceDashboardContactsViewIdRoute,
}

const AppWorkspaceDashboardRouteWithChildren =
  AppWorkspaceDashboardRoute._addFileChildren(
    AppWorkspaceDashboardRouteChildren,
  )

interface AppWorkspaceSettingsRouteChildren {
  AppWorkspaceSettingsBillingRoute: typeof AppWorkspaceSettingsBillingRoute
  AppWorkspaceSettingsMembersRoute: typeof AppWorkspaceSettingsMembersRoute
  AppWorkspaceSettingsPlansRoute: typeof AppWorkspaceSettingsPlansRoute
  AppWorkspaceSettingsTagsRoute: typeof AppWorkspaceSettingsTagsRoute
  AppWorkspaceSettingsWorkspaceRoute: typeof AppWorkspaceSettingsWorkspaceRoute
  AppWorkspaceSettingsIndexRoute: typeof AppWorkspaceSettingsIndexRoute
  AppWorkspaceSettingsAccountProfileRoute: typeof AppWorkspaceSettingsAccountProfileRoute
  AppWorkspaceSettingsAccountSecurityRoute: typeof AppWorkspaceSettingsAccountSecurityRoute
  AppWorkspaceSettingsAccountIndexRoute: typeof AppWorkspaceSettingsAccountIndexRoute
}

const AppWorkspaceSettingsRouteChildren: AppWorkspaceSettingsRouteChildren = {
  AppWorkspaceSettingsBillingRoute: AppWorkspaceSettingsBillingRoute,
  AppWorkspaceSettingsMembersRoute: AppWorkspaceSettingsMembersRoute,
  AppWorkspaceSettingsPlansRoute: AppWorkspaceSettingsPlansRoute,
  AppWorkspaceSettingsTagsRoute: AppWorkspaceSettingsTagsRoute,
  AppWorkspaceSettingsWorkspaceRoute: AppWorkspaceSettingsWorkspaceRoute,
  AppWorkspaceSettingsIndexRoute: AppWorkspaceSettingsIndexRoute,
  AppWorkspaceSettingsAccountProfileRoute:
    AppWorkspaceSettingsAccountProfileRoute,
  AppWorkspaceSettingsAccountSecurityRoute:
    AppWorkspaceSettingsAccountSecurityRoute,
  AppWorkspaceSettingsAccountIndexRoute: AppWorkspaceSettingsAccountIndexRoute,
}

const AppWorkspaceSettingsRouteWithChildren =
  AppWorkspaceSettingsRoute._addFileChildren(AppWorkspaceSettingsRouteChildren)

interface AppWorkspaceRouteChildren {
  AppWorkspaceDashboardRoute: typeof AppWorkspaceDashboardRouteWithChildren
  AppWorkspaceSettingsRoute: typeof AppWorkspaceSettingsRouteWithChildren
}

const AppWorkspaceRouteChildren: AppWorkspaceRouteChildren = {
  AppWorkspaceDashboardRoute: AppWorkspaceDashboardRouteWithChildren,
  AppWorkspaceSettingsRoute: AppWorkspaceSettingsRouteWithChildren,
}

const AppWorkspaceRouteWithChildren = AppWorkspaceRoute._addFileChildren(
  AppWorkspaceRouteChildren,
)

interface AppAcceptInviteRouteChildren {
  AppAcceptInviteTokenRoute: typeof AppAcceptInviteTokenRoute
}

const AppAcceptInviteRouteChildren: AppAcceptInviteRouteChildren = {
  AppAcceptInviteTokenRoute: AppAcceptInviteTokenRoute,
}

const AppAcceptInviteRouteWithChildren = AppAcceptInviteRoute._addFileChildren(
  AppAcceptInviteRouteChildren,
)

interface AppGettingStartedRouteChildren {
  AppGettingStartedIndexRoute: typeof AppGettingStartedIndexRoute
}

const AppGettingStartedRouteChildren: AppGettingStartedRouteChildren = {
  AppGettingStartedIndexRoute: AppGettingStartedIndexRoute,
}

const AppGettingStartedRouteWithChildren =
  AppGettingStartedRoute._addFileChildren(AppGettingStartedRouteChildren)

interface AppRouteChildren {
  AppWorkspaceRoute: typeof AppWorkspaceRouteWithChildren
  AppAcceptInviteRoute: typeof AppAcceptInviteRouteWithChildren
  AppGettingStartedRoute: typeof AppGettingStartedRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppWorkspaceRoute: AppWorkspaceRouteWithChildren,
  AppAcceptInviteRoute: AppAcceptInviteRouteWithChildren,
  AppGettingStartedRoute: AppGettingStartedRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiAuthSignUpRoute: ApiAuthSignUpRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
