export const readEmailHttpEnv = () => ({
  POSTMARK_WEBHOOK_USERNAME: process.env.POSTMARK_WEBHOOK_USERNAME,
  POSTMARK_WEBHOOK_PASSWORD: process.env.POSTMARK_WEBHOOK_PASSWORD,
  EMAIL_UNSUBSCRIBE_SECRET: process.env.EMAIL_UNSUBSCRIBE_SECRET,
});
