// Generated by the workflow publication commands. Do not edit release bindings.
import { publicationEchoV1Release } from "../../capabilities/_versions/publicationEcho/v1.release";
import { definePublicationRegistry } from "../_kit/publication";
import { publicationFixtureV1Release } from "../publicationFixture/v1.release";

export const workflowPublicationRegistry = definePublicationRegistry({
  capabilities: [publicationEchoV1Release],
  workflows: [publicationFixtureV1Release],
});
