import type { Document } from "@confect/server";
import type schemaDefinition from "./schema";

export type AccessAuditEventsDoc = Document.Document<typeof schemaDefinition, "accessAuditEvents">;
export type ActionApprovalsDoc = Document.Document<typeof schemaDefinition, "actionApprovals">;
export type ActionDigestsDoc = Document.Document<typeof schemaDefinition, "actionDigests">;
export type ActionJobsDoc = Document.Document<typeof schemaDefinition, "actionJobs">;
export type ActionTriggersDoc = Document.Document<typeof schemaDefinition, "actionTriggers">;
export type ApiKeysDoc = Document.Document<typeof schemaDefinition, "apiKeys">;
export type BillingPlansDoc = Document.Document<typeof schemaDefinition, "billingPlans">;
export type BrainPagesDoc = Document.Document<typeof schemaDefinition, "brainPages">;
export type BuildPackEntitlementsDoc = Document.Document<typeof schemaDefinition, "buildPackEntitlements">;
export type BuildPackExportsDoc = Document.Document<typeof schemaDefinition, "buildPackExports">;
export type BuildPackStagesDoc = Document.Document<typeof schemaDefinition, "buildPackStages">;
export type BuildPacksDoc = Document.Document<typeof schemaDefinition, "buildPacks">;
export type CheckoutSessionsDoc = Document.Document<typeof schemaDefinition, "checkoutSessions">;
export type CitationsDoc = Document.Document<typeof schemaDefinition, "citations">;
export type ClaimsDoc = Document.Document<typeof schemaDefinition, "claims">;
export type CommerceRevocationsDoc = Document.Document<typeof schemaDefinition, "commerceRevocations">;
export type ConceptsDoc = Document.Document<typeof schemaDefinition, "concepts">;
export type ContextPacksDoc = Document.Document<typeof schemaDefinition, "contextPacks">;
export type CreditLedgerDoc = Document.Document<typeof schemaDefinition, "creditLedger">;
export type DeployActionConsumptionsDoc = Document.Document<typeof schemaDefinition, "deployActionConsumptions">;
export type DeployApprovalsDoc = Document.Document<typeof schemaDefinition, "deployApprovals">;
export type DeployAuthorityAuditEventsDoc = Document.Document<typeof schemaDefinition, "deployAuthorityAuditEvents">;
export type DeployAuthorityIssuersDoc = Document.Document<typeof schemaDefinition, "deployAuthorityIssuers">;
export type DeployCensusSnapshotsDoc = Document.Document<typeof schemaDefinition, "deployCensusSnapshots">;
export type DeployVerdictsDoc = Document.Document<typeof schemaDefinition, "deployVerdicts">;
export type DocumentAnnotationsDoc = Document.Document<typeof schemaDefinition, "documentAnnotations">;
export type DocumentVersionsDoc = Document.Document<typeof schemaDefinition, "documentVersions">;
export type DocumentsDoc = Document.Document<typeof schemaDefinition, "documents">;
export type DsarRequestsDoc = Document.Document<typeof schemaDefinition, "dsarRequests">;
export type EmailVerificationChallengesDoc = Document.Document<typeof schemaDefinition, "emailVerificationChallenges">;
export type EntitlementsDoc = Document.Document<typeof schemaDefinition, "entitlements">;
export type EvaluationAnswersDoc = Document.Document<typeof schemaDefinition, "evaluationAnswers">;
export type EvaluationReportVersionsDoc = Document.Document<typeof schemaDefinition, "evaluationReportVersions">;
export type EvaluationReportsDoc = Document.Document<typeof schemaDefinition, "evaluationReports">;
export type EvaluationSessionsDoc = Document.Document<typeof schemaDefinition, "evaluationSessions">;
export type EvaluationSharesDoc = Document.Document<typeof schemaDefinition, "evaluationShares">;
export type FeatureFlagPoliciesDoc = Document.Document<typeof schemaDefinition, "featureFlagPolicies">;
export type InvitationsDoc = Document.Document<typeof schemaDefinition, "invitations">;
export type MaestroCreditsDoc = Document.Document<typeof schemaDefinition, "maestroCredits">;
export type ModelReceiptsDoc = Document.Document<typeof schemaDefinition, "modelReceipts">;
export type NotificationPreferencesDoc = Document.Document<typeof schemaDefinition, "notificationPreferences">;
export type NotificationRecordsDoc = Document.Document<typeof schemaDefinition, "notificationRecords">;
export type OrganizationMembersDoc = Document.Document<typeof schemaDefinition, "organizationMembers">;
export type OrganizationsDoc = Document.Document<typeof schemaDefinition, "organizations">;
export type PoliciesDoc = Document.Document<typeof schemaDefinition, "policies">;
export type PromptRegistryDoc = Document.Document<typeof schemaDefinition, "promptRegistry">;
export type PurchasesDoc = Document.Document<typeof schemaDefinition, "purchases">;
export type ReportOwnershipsDoc = Document.Document<typeof schemaDefinition, "reportOwnerships">;
export type SupportIncidentsDoc = Document.Document<typeof schemaDefinition, "supportIncidents">;
export type TransformBlocksDoc = Document.Document<typeof schemaDefinition, "transformBlocks">;
export type TransformDefinitionsDoc = Document.Document<typeof schemaDefinition, "transformDefinitions">;
export type TransformRunsDoc = Document.Document<typeof schemaDefinition, "transformRuns">;
export type UsageEventsDoc = Document.Document<typeof schemaDefinition, "usageEvents">;
export type UsersDoc = Document.Document<typeof schemaDefinition, "users">;
export type VersionFreshnessDoc = Document.Document<typeof schemaDefinition, "versionFreshness">;
export type VersionedEntriesDoc = Document.Document<typeof schemaDefinition, "versionedEntries">;
export type WebhookEventsDoc = Document.Document<typeof schemaDefinition, "webhookEvents">;
export type WorkflowArtifactsDoc = Document.Document<typeof schemaDefinition, "workflowArtifacts">;
export type WorkflowEffectReservationsDoc = Document.Document<typeof schemaDefinition, "workflowEffectReservations">;
export type WorkflowEventInstancesDoc = Document.Document<typeof schemaDefinition, "workflowEventInstances">;
export type WorkflowRunContextManifestsDoc = Document.Document<typeof schemaDefinition, "workflowRunContextManifests">;
export type WorkflowRunEventsDoc = Document.Document<typeof schemaDefinition, "workflowRunEvents">;
export type WorkflowRunEvidenceSnapshotsDoc = Document.Document<typeof schemaDefinition, "workflowRunEvidenceSnapshots">;
export type WorkflowRunLinksDoc = Document.Document<typeof schemaDefinition, "workflowRunLinks">;
export type WorkflowRunsDoc = Document.Document<typeof schemaDefinition, "workflowRuns">;
export type WorkflowStageRunsDoc = Document.Document<typeof schemaDefinition, "workflowStageRuns">;
export type WorkspaceMembersDoc = Document.Document<typeof schemaDefinition, "workspaceMembers">;
export type WorkspacesDoc = Document.Document<typeof schemaDefinition, "workspaces">;

export interface Docs {
  accessAuditEvents: AccessAuditEventsDoc;
  actionApprovals: ActionApprovalsDoc;
  actionDigests: ActionDigestsDoc;
  actionJobs: ActionJobsDoc;
  actionTriggers: ActionTriggersDoc;
  apiKeys: ApiKeysDoc;
  billingPlans: BillingPlansDoc;
  brainPages: BrainPagesDoc;
  buildPackEntitlements: BuildPackEntitlementsDoc;
  buildPackExports: BuildPackExportsDoc;
  buildPackStages: BuildPackStagesDoc;
  buildPacks: BuildPacksDoc;
  checkoutSessions: CheckoutSessionsDoc;
  citations: CitationsDoc;
  claims: ClaimsDoc;
  commerceRevocations: CommerceRevocationsDoc;
  concepts: ConceptsDoc;
  contextPacks: ContextPacksDoc;
  creditLedger: CreditLedgerDoc;
  deployActionConsumptions: DeployActionConsumptionsDoc;
  deployApprovals: DeployApprovalsDoc;
  deployAuthorityAuditEvents: DeployAuthorityAuditEventsDoc;
  deployAuthorityIssuers: DeployAuthorityIssuersDoc;
  deployCensusSnapshots: DeployCensusSnapshotsDoc;
  deployVerdicts: DeployVerdictsDoc;
  documentAnnotations: DocumentAnnotationsDoc;
  documentVersions: DocumentVersionsDoc;
  documents: DocumentsDoc;
  dsarRequests: DsarRequestsDoc;
  emailVerificationChallenges: EmailVerificationChallengesDoc;
  entitlements: EntitlementsDoc;
  evaluationAnswers: EvaluationAnswersDoc;
  evaluationReportVersions: EvaluationReportVersionsDoc;
  evaluationReports: EvaluationReportsDoc;
  evaluationSessions: EvaluationSessionsDoc;
  evaluationShares: EvaluationSharesDoc;
  featureFlagPolicies: FeatureFlagPoliciesDoc;
  invitations: InvitationsDoc;
  maestroCredits: MaestroCreditsDoc;
  modelReceipts: ModelReceiptsDoc;
  notificationPreferences: NotificationPreferencesDoc;
  notificationRecords: NotificationRecordsDoc;
  organizationMembers: OrganizationMembersDoc;
  organizations: OrganizationsDoc;
  policies: PoliciesDoc;
  promptRegistry: PromptRegistryDoc;
  purchases: PurchasesDoc;
  reportOwnerships: ReportOwnershipsDoc;
  supportIncidents: SupportIncidentsDoc;
  transformBlocks: TransformBlocksDoc;
  transformDefinitions: TransformDefinitionsDoc;
  transformRuns: TransformRunsDoc;
  usageEvents: UsageEventsDoc;
  users: UsersDoc;
  versionFreshness: VersionFreshnessDoc;
  versionedEntries: VersionedEntriesDoc;
  webhookEvents: WebhookEventsDoc;
  workflowArtifacts: WorkflowArtifactsDoc;
  workflowEffectReservations: WorkflowEffectReservationsDoc;
  workflowEventInstances: WorkflowEventInstancesDoc;
  workflowRunContextManifests: WorkflowRunContextManifestsDoc;
  workflowRunEvents: WorkflowRunEventsDoc;
  workflowRunEvidenceSnapshots: WorkflowRunEvidenceSnapshotsDoc;
  workflowRunLinks: WorkflowRunLinksDoc;
  workflowRuns: WorkflowRunsDoc;
  workflowStageRuns: WorkflowStageRunsDoc;
  workspaceMembers: WorkspaceMembersDoc;
  workspaces: WorkspacesDoc;
}
