export const STARTER_COMMIT =
  "b76cb4514b9ab47f7db87901cb9b593b4adc3129" as const;

const source = (path: string) => ({
  source: `apps/web/src/${path}`,
  destination: `src/${path}`,
});

const publicSource = (path: string) => ({
  source: `apps/web/public/${path}`,
  destination: `public/${path}`,
});

export const starterCompositions = {
  theme: [
    source("theme/preset.ts"),
    source("theme/semantic-tokens/colors.ts"),
    source("config/hotkeys.config.ts"),
  ],
  provider: [
    source("features/common/providers/app-provider.tsx"),
    source("features/common/components/hotkeys.tsx"),
    source("hooks/use-open-state.ts"),
  ],
  shell: [
    source("features/common/layouts/app-layout.tsx"),
    source("features/common/layouts/dashboard-layout.tsx"),
    source("features/common/layouts/fullscreen-layout.tsx"),
    source("features/common/components/app-sidebar.tsx"),
    source("features/common/components/user-menu.tsx"),
    source("features/common/components/workspaces-menu.tsx"),
    source("features/common/components/global-search-input.tsx"),
    source("features/common/components/sidebar-tags.tsx"),
    source("features/common/components/billing-status.tsx"),
    source("features/common/components/invite-people.tsx"),
    source("features/common/hooks/use-current-user.ts"),
    source("features/common/hooks/use-current-workspace.ts"),
    source("features/common/hooks/use-workspace-slug.ts"),
    source("features/common/hooks/use-workspaces.ts"),
    source("features/common/hooks/use-tags.ts"),
    source("features/common/util/get-base-url.ts"),
  ],
  routes: [
    source("router.tsx"),
    source("routeTree.gen.ts"),
    ...[
      "__root.tsx",
      "_app.tsx",
      "_app/index.tsx",
      "_app/accept-invite.tsx",
      "_app/accept-invite/$token.tsx",
      "_app/getting-started.tsx",
      "_app/getting-started/index.tsx",
      "_app/$workspace.tsx",
      "_app/$workspace/_dashboard.tsx",
      "_app/$workspace/_dashboard/index.tsx",
      "_app/$workspace/_dashboard/contacts/index.tsx",
      "_app/$workspace/_dashboard/contacts/$type.tsx",
      "_app/$workspace/_dashboard/contacts/view/$id.tsx",
      "_app/$workspace/_dashboard/inbox.tsx",
      "_app/$workspace/_dashboard/inbox/$id.tsx",
      "_app/$workspace/_dashboard/search.tsx",
      "_app/$workspace/_dashboard/tag/$tag.tsx",
      "_app/$workspace/settings.tsx",
      "_app/$workspace/settings/index.tsx",
      "_app/$workspace/settings/account/index.tsx",
      "_app/$workspace/settings/account/profile.tsx",
      "_app/$workspace/settings/account/security.tsx",
      "_app/$workspace/settings/billing.tsx",
      "_app/$workspace/settings/members.tsx",
      "_app/$workspace/settings/plans.tsx",
      "_app/$workspace/settings/tags.tsx",
      "_app/$workspace/settings/workspace.tsx",
      "_auth.tsx",
      "_auth/forgot-password.tsx",
      "_auth/login.tsx",
      "_auth/reset-password.tsx",
      "_auth/signup.tsx",
      "api/auth/$.ts",
      "api/trpc/$.ts",
      "api/webhooks/stripe.tsx",
    ].map((path) => source(`routes/${path}`)),
  ],
  archetypes: [
    source("components/default-error-page.tsx"),
    source("components/default-loader.tsx"),
    source("components/link-button.tsx"),
    source("components/link.tsx"),
    source("lib/last-used-workspace.ts"),
    source("lib/react-query.ts"),
    source("lib/trpc/react.tsx"),
    source("lib/trpc/utils.ts"),
    source("lib/user-settings/use-user-settings.ts"),
    publicSource("img/onboarding/light.svg"),
    publicSource("img/onboarding/dark.svg"),
    ...[
      "contacts/common/contact-avatar.tsx",
      "contacts/common/contact-status.tsx",
      "contacts/common/contact-tag.tsx",
      "contacts/common/contact-type.tsx",
      "contacts/inbox/inbox-layout.tsx",
      "contacts/inbox/inbox-list.tsx",
      "contacts/inbox/inbox-view-page.tsx",
      "contacts/inbox/inbox.not-found.tsx",
      "contacts/list/add-person-dialog.tsx",
      "contacts/list/contact-board-header.tsx",
      "contacts/list/contact-bulk-actions.tsx",
      "contacts/list/contact-card.tsx",
      "contacts/list/contact-filters.tsx",
      "contacts/list/contact-types.tsx",
      "contacts/list/get-contact-type.ts",
      "contacts/list/list-page.tsx",
      "contacts/view/activities-panel.tsx",
      "contacts/view/activity-timeline.tsx",
      "contacts/view/contact-page.tsx",
      "contacts/view/contact-sidebar.tsx",
      "contacts/view/contact-tags.tsx",
      "contacts/view/contact.error.tsx",
      "contacts/view/contact.not-found.tsx",
      "reports/reports-page.tsx",
      "reports/metrics/activity.tsx",
      "reports/metrics/metric.tsx",
      "reports/metrics/metrics-card.tsx",
      "reports/metrics/revenue-chart.tsx",
      "reports/metrics/sales-by-country.tsx",
      "settings/account/account-api-page.tsx",
      "settings/account/account-notifications-page.tsx",
      "settings/account/account-profile-page.tsx",
      "settings/account/account-security-page.tsx",
      "settings/account/index.ts",
      "settings/account/update-password-dialog.tsx",
      "settings/account/schema/profile.schema.ts",
      "settings/account/schema/update-password.schema.ts",
      "settings/billing/billing-page.tsx",
      "settings/billing/billing-status.tsx",
      "settings/billing/manage-billing-button.tsx",
      "settings/billing/plans-page.tsx",
      "settings/common/settings-card.tsx",
      "settings/common/settings-layout.tsx",
      "settings/common/settings-sidebar.tsx",
      "settings/common/support-card.tsx",
      "settings/members/members-list.tsx",
      "settings/members/members-page.tsx",
      "settings/tags/color-control.tsx",
      "settings/tags/manage-tags.tsx",
      "settings/tags/tags-settings-page.tsx",
      "settings/workspace/workspace-settings-page.tsx",
      "getting-started/appearance.tsx",
      "getting-started/create-workspace.tsx",
      "getting-started/getting-started-page.tsx",
      "getting-started/index.ts",
      "getting-started/invite-team-members.tsx",
      "getting-started/onboarding-layout.tsx",
      "getting-started/onboarding-step.tsx",
      "getting-started/subscribe.tsx",
      "getting-started/schema/appearance.schema.ts",
      "getting-started/schema/invite-team.schema.ts",
      "getting-started/schema/subscribe.schema.ts",
      "getting-started/schema/workspace.schema.ts",
      "auth/auth-layout.tsx",
      "auth/auth-provider.tsx",
      "auth/forgot-password-page.tsx",
      "auth/login-page.tsx",
      "auth/reset-password-page.tsx",
      "auth/signup-page.tsx",
      "auth/components/auth-card.tsx",
      "auth/components/last-used.tsx",
      "auth/components/providers.tsx",
      "auth/components/testimonial.tsx",
      "auth/schema/forgot-password.schema.ts",
      "auth/schema/login.schema.ts",
      "auth/schema/password.schema.ts",
      "auth/schema/reset-password.schema.ts",
      "auth/schema/signup.schema.ts",
      "billing/components/payment-overdue-banner.tsx",
      "billing/components/pricing-table.tsx",
      "billing/hooks/use-plans.ts",
      "billing/providers/billing-provider.tsx",
      "search/search-page.tsx",
      "workspaces/workspace.loading.tsx",
      "workspaces/workspace.not-found.tsx",
      "workspaces/invite/accept-invite-page.tsx",
    ].map((path) => source(`features/${path}`)),
  ],
} as const;

export type StarterCompositionId = keyof typeof starterCompositions;

export const starterFiles = (ids: readonly string[]) =>
  ids.flatMap((id) => {
    if (!(id in starterCompositions)) {
      throw new Error(`Unknown starter composition: ${id}`);
    }
    return starterCompositions[id as StarterCompositionId];
  });
