import { componentsGeneric } from "convex/server";

type WorkflowDeadlineApi =
  import("../../../convex/components/workflowDeadline/_generated/component.js").ComponentApi<"workflowDeadline">;
type WorkflowAdmissionApi =
  import("../../../convex/components/workflowAdmission/_generated/component.js").ComponentApi<"workflowAdmission">;
type WorkpoolApi =
  import("@convex-dev/workpool/_generated/component.js").ComponentApi<"workflowDeadlineWorkpool">;
type WorkflowApi =
  import("@convex-dev/workflow/_generated/component.js").ComponentApi<"workflow">;

/**
 * Current root component references used by the Confect-owned deadline group.
 * The API types remain generated by each component; this authored projection
 * only gives `componentsGeneric()` the app installation names from
 * `convex/convex.config.ts`.
 */
export const localWorkflowComponents = componentsGeneric() as unknown as {
  readonly workflowDeadline: WorkflowDeadlineApi;
  readonly workflowAdmission: WorkflowAdmissionApi;
  readonly workflowDeadlineWorkpool: WorkpoolApi;
  readonly workflow: WorkflowApi;
};
